# Boiler plate template for docker-compose.yml

services:
  
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    volumes:
      - ./postgres-db/postgres_volume:/usr/local/pgsql/data
      - ./postgres-db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:3321:3305"
    networks:
      - local-net

  api:
    build: ./api
    container_name: fastapi-backend
    environment:
      PORT: 8000
    ports:
      - '127.0.0.1:3000:8000'
    restart: always
    depends_on: # defines startup and shutdown dependencies between services.
      - postgres-db
    networks:
      - local-net


networks:
  local-net:
    driver: bridge